apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "quick-monitor.fullname" . }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
      - events
      - "pods/portforward"
  - verbs:
      - 'create'
    apiGroups:
      - ''
    resources:
      - pods/exec
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods/log
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - apps
    resources:
      - '*'
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - configmaps
      - jobs
      - services
      - persistentvolumes
      - persistentvolumeclaims
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
