apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "quick-monitor.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "quick-monitor.fullname" . }}
  namespace: quick
roleRef:
  kind: ClusterRole
  name: {{ include "quick-monitor.fullname" . }}
  apiGroup: rbac.authorization.k8s.io